import "./globals.css";
import { PropsWithChildren, ReactNode } from "react";
import { Metadata } from "next";
import { cx } from "class-variance-authority";
import { lineFont, poppins } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props extends PropsWithChildren {
  authModal: ReactNode;
}
export default function RootLayout({ authModal, children }: Props) {
  return (
    <html lang={"en"} className={"border-8"}>
      <body className={cx(lineFont.className, poppins.variable)}>
        {children}
        {authModal}
      </body>
    </html>
  );
}
