import "../globals.css";
import { notFound } from "next/navigation";
import { PropsWithChildren } from "react";
import { Inter, Poppins } from "next/font/google";
import { Metadata } from "next";
import { cn } from "@/utils/cn";
import { unstable_setRequestLocale } from "next-intl/server";
import { LOCALES } from "@/constants/LOCALES";

export function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}

const inter = Inter({
  variable: "--inter-font",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--poppins-font",
  subsets: ["latin"],
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props extends PropsWithChildren {
  params: { locale: (typeof LOCALES)[number] };
}
export default function LocaleLayout({ children, params: { locale } }: Props) {
  const isValidLocale = LOCALES.some((cur) => cur === locale);
  if (!isValidLocale) notFound();

  unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={cn(inter.className, poppins.variable)}>{children}</body>
    </html>
  );
}
