import "../globals.css";
import { notFound } from "next/navigation";
import { PropsWithChildren } from "react";
import { Metadata } from "next";
import { unstable_setRequestLocale } from "next-intl/server";
import { LOCALES } from "@/constants/LOCALES";
import { cx } from "class-variance-authority";
import { lineFont, poppins } from "@/app/fonts";

export function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props extends PropsWithChildren {
  params: { locale: (typeof LOCALES)[number] };
}
export default function LocaleLayout({ children, params: { locale } }: Props) {
  const isValidLocale = LOCALES.some((cur) => cur === locale);
  if (!isValidLocale) notFound();

  unstable_setRequestLocale(locale);

  return (
    <html lang={locale} className={"border-8"}>
      <body className={cx(lineFont.className, poppins.variable)}>
        {children}
      </body>
    </html>
  );
}
